<a href="https://colab.research.google.com/github/Shrinivas18/Python_Coding_Problems/blob/main/Finding_Closest_Pairs_using_Euclidian_Distance_and_Manhattan_Distance_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### In this problem, we are going to calculate distances between some pairs of points :

### <u> Measures of distances </u>
* ### Euclidean Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)={\sqrt {(x_{1}-x_{2})^{2}+(y_{1}-y_{2})^{2}}}.}$

* ### Manhattan Distance : The distance between two points $(x_{1},y_{1})$ , $(x_{2},y_{2})$ is defined as :
${\displaystyle d(x,y)=|x_{1}-x_{2}|+|y_{1}-y_{2}|}$


## Find the closest pairs (excluding self pairs) on the basis of both the distance measures

In [1]:
# Importing numpy and math libraries.
import math
import numpy as np

In [2]:
# Creating random points.

points=np.random.randint(5,20,(10,2))
print(points)

[[13 11]
 [11 17]
 [18 19]
 [17 17]
 [14 17]
 [ 7 15]
 [12 10]
 [18 12]
 [18  8]
 [15  5]]


In [3]:
# Calculating Euclidian distance.

def distance_ed(p1,p2):
  return round(math.sqrt((p1[0]-p2[0])**2+(p1[1]-p2[1])**2),2) 

In [4]:
# Calculating minimum distances between all points using Euclidian Distance.

def euclidian_distance(points):
  n=len(points)
  x=[]
  for i in range(n):
    for j in range(n):
      d=distance_ed(points[i],points[j])
      x.append(d)
    
  return (np.reshape(x,(10,10)))

In [5]:
# Displaying minimum distances between all points using Euclidian Distance.

print((euclidian_distance(points)))

[[ 0.    6.32  9.43  7.21  6.08  7.21  1.41  5.1   5.83  6.32]
 [ 6.32  0.    7.28  6.    3.    4.47  7.07  8.6  11.4  12.65]
 [ 9.43  7.28  0.    2.24  4.47 11.7  10.82  7.   11.   14.32]
 [ 7.21  6.    2.24  0.    3.   10.2   8.6   5.1   9.06 12.17]
 [ 6.08  3.    4.47  3.    0.    7.28  7.28  6.4   9.85 12.04]
 [ 7.21  4.47 11.7  10.2   7.28  0.    7.07 11.4  13.04 12.81]
 [ 1.41  7.07 10.82  8.6   7.28  7.07  0.    6.32  6.32  5.83]
 [ 5.1   8.6   7.    5.1   6.4  11.4   6.32  0.    4.    7.62]
 [ 5.83 11.4  11.    9.06  9.85 13.04  6.32  4.    0.    4.24]
 [ 6.32 12.65 14.32 12.17 12.04 12.81  5.83  7.62  4.24  0.  ]]


In [6]:
# Calculating Manhattan Distance between two points.

def distance_md(p1,p2):
  return (abs(p1[0]-p2[0])+abs(p1[1]-p2[1]))

In [7]:
# Calculating minimum distances between all points using Manhattan Distance.

def manhattan_distance(points):
  n=len(points)
  x=[]
  for i in range(n):
    for j in range(n):
      d=distance_md(points[i],points[j])
      x.append(d)
  return(np.reshape(x,(10,10)))
  

In [8]:
# Displaying minimum distances between all points using Manhattan Distance.

print(manhattan_distance(points))

[[ 0  8 13 10  7 10  2  6  8  8]
 [ 8  0  9  6  3  6  8 12 16 16]
 [13  9  0  3  6 15 15  7 11 17]
 [10  6  3  0  3 12 12  6 10 14]
 [ 7  3  6  3  0  9  9  9 13 13]
 [10  6 15 12  9  0 10 14 18 18]
 [ 2  8 15 12  9 10  0  8  8  8]
 [ 6 12  7  6  9 14  8  0  4 10]
 [ 8 16 11 10 13 18  8  4  0  6]
 [ 8 16 17 14 13 18  8 10  6  0]]


In [9]:
# Minimal Distance between points using Euclidian Distance

def min_ed(points):
  n=len(points)
  nded=(None,None)
  a=[]

  for i in range(n):
    minimum=float('inf')
    for j in range(i+1,n):
      d=distance_ed(points[i],points[j])
      if d < minimum:
        minimum=d
        nded=(points[i],points[j])
    a.append(nded)

  
  return a



In [10]:
# Minimal Distance between points using Manhattan Distance


def min_md(points):
  n=len(points)
  mded=(None,None)
  x=[]

  for i in range(n):
    minimum=float('inf')
    for j in range(i+1,n):
      d=distance_md(points[i],points[j])

      if d < minimum:
        minimum=d
        mded=(points[i],points[j])
    x.append(mded)
  
  return x


In [11]:
# Displaying minimal Distance between points using Euclidian Distance.

print(min_ed(points))


[(array([13, 11]), array([12, 10])), (array([11, 17]), array([14, 17])), (array([18, 19]), array([17, 17])), (array([17, 17]), array([14, 17])), (array([14, 17]), array([18, 12])), (array([ 7, 15]), array([12, 10])), (array([12, 10]), array([15,  5])), (array([18, 12]), array([18,  8])), (array([18,  8]), array([15,  5])), (array([18,  8]), array([15,  5]))]


In [12]:
# Displaying minimal Distance between points using Manhattan Distance.

print(min_md(points))


[(array([13, 11]), array([12, 10])), (array([11, 17]), array([14, 17])), (array([18, 19]), array([17, 17])), (array([17, 17]), array([14, 17])), (array([14, 17]), array([ 7, 15])), (array([ 7, 15]), array([12, 10])), (array([12, 10]), array([18, 12])), (array([18, 12]), array([18,  8])), (array([18,  8]), array([15,  5])), (array([18,  8]), array([15,  5]))]
