<a href="https://colab.research.google.com/github/Shrinivas18/Python_Coding_Problems/blob/main/Rotate_the_2D_matrix_by_90_degree_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROBLEM :**

You are given an (n x n) 2D matrix representing an image, rotate the image by 90 degrees (clockwise).

You have to rotate the image in-place, which means you have to modify the input 2D matrix directly.

DO NOT allocate another 2D matrix and do the rotation.




In [11]:
import numpy as np

def rotate(matrix):
    n = len(matrix)
 
    # Transpose the matrix
    for i in range(n):  # Iterate over the rows
        for j in range(i, n):  # Iterate over the columns starting from the current row 'i'
            # Swap the elements at positions (i, j) and (j, i)
            matrix[i][j], matrix[j][i] = matrix[j][i], matrix[i][j]
 
    # Reverse each row
    for row in matrix:  # Iterate over each row in the matrix
        row.reverse()  # Reverse the elements in the current row
    return np.array(matrix)

x=int(input("Number of rows/columns in an array : "))
matrix=[]
for i in range(x):
  a=[]
  for j in range(x):
    a.append(int(input("Element : ")))

  matrix.append(a)

print("\nMatrix is : \n")
print(np.array(matrix))
print("\nThe rotated matrix is : \n")
print(rotate(matrix))

Number of rows/columns in an array : 3
Element : 1
Element : 2
Element : 3
Element : 4
Element : 5
Element : 6
Element : 7
Element : 8
Element : 9

Matrix is : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The rotated matrix is : 

[[7 4 1]
 [8 5 2]
 [9 6 3]]
