<a href="https://colab.research.google.com/github/Shrinivas18/Python_Coding_Problems/blob/main/Sum_of_diagonal_elements_in_an_array_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**PROBLEM :**

Given 2D list calculate the sum of diagonal elements.




In [15]:
import numpy as np

def diagonal_sum(matrix):
    # Initialize the sum to 0
    total = 0
 
    # Iterate through the rows of the matrix
    for i in range(len(matrix)):
        # Add the diagonal element to the total sum
        total += matrix[i][i]
 
    return total

x=int(input("Number of rows/columns in an array : "))
matrix=[]
for i in range(x):
  a=[]
  for j in range(x):
    a.append(int(input("Element : ")))

  matrix.append(a)

print("\nMatrix is : \n")
print(np.array(matrix))
print("\nThe sum of diagonal of matrix : ",diagonal_sum(matrix))

Number of rows/columns in an array : 3
Element : 1
Element : 2
Element : 3
Element : 4
Element : 5
Element : 6
Element : 7
Element : 8
Element : 9

Matrix is : 

[[1 2 3]
 [4 5 6]
 [7 8 9]]

The sum of diagonal of matrix :  15
